language: go

go:
  - 1.10.x
  - tip

before_install:
  - curl https://glide.sh/get | sh
  - glide install

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make test
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
